### PR TITLE
conf: add port to throw-to-launch command sending

### PR DESCRIPTION
**Pull request by TSC21**
Adds port so that the button scripts can send/rcv MAVLink msgs and commands (ex: throw-to-launch activation).

### CODE REVIEW

**Comment by TSC21** [comment]
Note that I chose port 14570 for no reason in specific.

**Comment by cwteal** [comment]
Looks good to me, but I'm a novice still.

**Review by themcfadden — APPROVED** [review]
Looks good.

**Comment by TSC21** [comment]
@hunterino can we bring this in?

**Pull request merged**
